# Generated by Django 5.0.7 on 2024-09-23 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_systemcategory_systemmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="staritems",
            name="starsystem",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="myapp.systemmodel",
            ),
        ),
    ]
