# Generated by Django 5.0.7 on 2024-09-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_systemmodel_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="planetitems",
            name="summary",
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name="staritems",
            name="summary",
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name="systemmodel",
            name="summary",
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
