# Generated by Django 5.0.7 on 2024-09-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_planetitems_summary_staritems_summary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="planetitems",
            name="url",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="staritems",
            name="url",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="systemmodel",
            name="url",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
