# Generated by Django 5.0.7 on 2024-10-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_planetitems_url_staritems_url_systemmodel_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="staritems",
            name="radius",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
