# Generated by Django 5.0.7 on 2024-10-05 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0009_urlmodel_url_alter_urlmodel_content_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="urlmodel",
            old_name="url",
            new_name="custom_url",
        ),
    ]
