# Generated by Django 5.0.7 on 2024-10-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0010_rename_url_urlmodel_custom_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="planetitems",
            name="atmos",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="planetitems",
            name="classification",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="planetitems",
            name="conditions",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="planetitems",
            name="gravity",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="planetitems",
            name="magnetic",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="planetitems",
            name="mass",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="planetitems",
            name="orbit",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="planetitems",
            name="radius",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="planetitems",
            name="transit",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
