# Generated by Django 5.0.7 on 2024-10-06 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0012_staritems_age_staritems_lumi_staritems_magnetic_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UrlModel",
        ),
    ]
