# Generated by Django 5.0.7 on 2024-09-19 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planetitems",
            name="category",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="myapp.planetcategory",
            ),
        ),
        migrations.AlterField(
            model_name="planetitems",
            name="star",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="myapp.staritems",
            ),
        ),
        migrations.AlterField(
            model_name="staritems",
            name="category",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="myapp.starcategory",
            ),
        ),
    ]
